### PR TITLE
Fixes default value handling

### LINKED ISSUE #4: Fix default value handling in CQRS controllers
## Symptoms

The REST API responds with as `500 Server Error`.

## How to Reproduce

In EDD Bookings:
- Navigate to the bookings list or calendar page
- Create or edit a booking
- Open your browser dev tools
- Find the Networking panel
- Clear the payment number field in the booking modal, leaving it empty
- Clear the Networking panel log
- Save the booking
- An entry should appear in the Networking panel for a REST API request
- After some time, the response should come back with a `500` status code

For further validation:
- Click the entry and find the Response (or "Preview" in Chrome) panels
- There should be an error message that reads: _"Not a stringable value"_

## Possible Cause

If an empty value present in the request, it will be normalized to `null`. This results in errors since the values are attempted to be normalized to strings when the SQL query is being generated.

## The Solution

Add null value handling for values accepted in CQRS controllers. Each value should have a meaningful default that can be stringified and is a valid SQL query value.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #4

### CODE REVIEW

File: src/Controller/BookingsController.php [hunk 1]
```diff
@@ -500,30 +500,75 @@ protected function _getUpdateParamFieldMapping()
         return [
             'start' => [
                 'field'     => 'start',
-                'transform' => [$this, '_parseIso8601'],
+                'transform' => function ($value) {
+                    if (empty($value)) {
```
Comment (XedinUnknown) [inline src/Controller/BookingsController.php:504]: Looks like there's validation logic here. I don't think it belongs here at all. Could this be approached  differently? Perhaps by using a validator?

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

File: src/Controller/BookingsController.php (hunk 1 above)
Comment (mecha) [reply src/Controller/BookingsController.php:504]: Perhaps.

Comment (mecha) [reply src/Controller/BookingsController.php:504]: Created https://github.com/RebelCode/rcmod-eddbk-rest-api/issues/7

**Review by XedinUnknown — APPROVED** [review]
